import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";
import SessionMenu from "@/components/session-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient();
  const { data: userData } = await supabase.auth.getUser();
  let profile: { full_name?: string } | null = null;
  if (userData.user) {
    const { data } = await supabase.from("profiles").select("full_name").eq("id", userData.user.id).single();
    profile = data || null;
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b bg-background/50">
          <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3">
            <a href="/" className="text-lg font-semibold">
              Assisto
            </a>
            <nav className="flex items-center gap-3 text-sm">
              <a href="/discover" className="rounded-full border px-3 py-1">
                Discover
              </a>
              <a href="/requirements/new" className="rounded-full border px-3 py-1">
                Describe need
              </a>
              <a href="/apply" className="rounded-full border px-3 py-1">
                Apply
              </a>
            </nav>
            <div>
              <SessionMenu userId={userData.user?.id} fullName={profile?.full_name} />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
